### ISSUE TITLE
Add an option to hide the timer while keeping it counting

### ISSUE THREAD

**Issue by akien-mga** [rgrams/ross_project_timer#3]
I think some users might be interested in knowing how much time they spend on a given project, while not wanting to see the timer increasing in the edge of their eyesight all the time. I find it personally quite distracting :)

Two options to improve this:
- add a possibility to disable seconds display, so it would only update every 60 s, which is way less distracting (just like system clock)
- add a possibility to hide the timer, but keep it counting. It could e.g. replace the text of the option button with the name of the plugin

**Comment by rgrams** [comment]
Good points! I'll add an option to not show seconds. Maybe the second option would be to only show the time on mouseover?

**Comment by akien-mga** [comment]
Sounds good yes :)

**Comment by rgrams** [comment]
Okay, I think that should do it, for this issue and #2. Now there are check boxes in the menu for showing/hiding the seconds digits, and to only show the time when you mouseover the widget. I put in a slightly slapdash little stopwatch icon for the latter, so it's not just a blank button most of the time. I also added a little pause icon, so that is always obvious, and an option to disable the pulsing pause animation, which takes the CPU usage down to 0. 
The pause icon makes it a little cramped if you get up into five-digit numbers of hours, haha, but I somehow doubt that will be a problem for anyone.
